In [1]:
# reshaping , viewing, stacking, squeezing and unsqueezing

import torch

a = torch.tensor([1,2,3,4,5,6])
print('before reshape : ',a)

a = a.reshape([3,2])
print('after reshape : ',a)

b = torch.tensor([1,2,3,4,5,6,7,8,9])
print('view: ' ,b.view(3,3))

c1= torch.tensor([1,2,3])
c2 = torch.tensor([4,5,6])
c = torch.stack((c1,c2), dim=0)
print('stack (dim 0): \n' ,c)

c = torch.stack((c1,c2), dim=1)
print('stack (dim 1): \n' ,c)


d1 = torch.randn(3,1,2,1,5)
d = torch.squeeze(d1)
print('d.size() = ',d.size())

e1 = torch.arange(8, dtype=torch.float)
print('e1 = ', e1)

e = torch.unsqueeze(e1, dim=0)
print('unsqueeze dim =0 :  ', e.size())

e = torch.unsqueeze(e1, dim=1)
print('unsqueeze dim =1 :  ', e.size())

before reshape :  tensor([1, 2, 3, 4, 5, 6])
after reshape :  tensor([[1, 2],
        [3, 4],
        [5, 6]])
view:  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
stack (dim 0): 
 tensor([[1, 2, 3],
        [4, 5, 6]])
stack (dim 1): 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
d.size() =  torch.Size([3, 2, 5])
e1 =  tensor([0., 1., 2., 3., 4., 5., 6., 7.])
unsqueeze dim =0 :   torch.Size([1, 8])
unsqueeze dim =1 :   torch.Size([8, 1])


In [2]:
# use of permute
# import pytorch library
import torch

# creating a tensor with random
# values of dimension 3 X 5 X 2
input_var = torch.randn(3, 5, 2)

# print size
print(input_var.size())

print(input_var)

# dimensions permuted
input_var = input_var.permute(2, 0, 1)

# print size
print(input_var.size())

print(input_var)

torch.Size([3, 5, 2])
tensor([[[ 1.0467, -0.6281],
         [-0.3758, -0.2296],
         [ 1.8729,  0.7482],
         [ 1.7604, -0.3294],
         [-0.3236,  0.8756]],

        [[-0.4601,  0.9111],
         [-1.0745, -0.1432],
         [-0.1623,  0.0815],
         [-0.0564,  1.6636],
         [-0.0957, -0.1189]],

        [[ 1.3231, -0.4398],
         [-1.2671,  0.3552],
         [ 0.4504,  0.4286],
         [-0.2312, -1.0840],
         [-0.3573,  0.3979]]])
torch.Size([2, 3, 5])
tensor([[[ 1.0467, -0.3758,  1.8729,  1.7604, -0.3236],
         [-0.4601, -1.0745, -0.1623, -0.0564, -0.0957],
         [ 1.3231, -1.2671,  0.4504, -0.2312, -0.3573]],

        [[-0.6281, -0.2296,  0.7482, -0.3294,  0.8756],
         [ 0.9111, -0.1432,  0.0815,  1.6636, -0.1189],
         [-0.4398,  0.3552,  0.4286, -1.0840,  0.3979]]])


In [3]:
# indexing

import torch

tensor = torch.tensor([[1,5,3],[8,9,2]])

print(tensor)

print('at 1,0 = ' ,tensor[1,0])
print('at 1 = ' ,tensor[1])

tensor([[1, 5, 3],
        [8, 9, 2]])
at 1,0 =  tensor(8)
at 1 =  tensor([8, 9, 2])


In [4]:
# numpy array to tensor and back to numpy array
import torch
import numpy as np

npx = np.array([[1,2,3],[5,6,6], [7,8,9]])
print(npx, type(npx))

# change to tensor
t = torch.from_numpy(npx)

print(t, type(t))

npy = t.numpy()

print(npy, type(npy))

[[1 2 3]
 [5 6 6]
 [7 8 9]] <class 'numpy.ndarray'>
tensor([[1, 2, 3],
        [5, 6, 6],
        [7, 8, 9]]) <class 'torch.Tensor'>
[[1 2 3]
 [5 6 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [5]:
# random tensor of size 7 X 7
import torch

random_tensor = torch.rand(7,7)

print(random_tensor, random_tensor.shape)

tensor([[0.0393, 0.6057, 0.4062, 0.8650, 0.6936, 0.3913, 0.9383],
        [0.1498, 0.4351, 0.8501, 0.8986, 0.8936, 0.2534, 0.5907],
        [0.5854, 0.9427, 0.8154, 0.2142, 0.9779, 0.0123, 0.9049],
        [0.2148, 0.3298, 0.7098, 0.8109, 0.6662, 0.2799, 0.8792],
        [0.1247, 0.8659, 0.1967, 0.8992, 0.5963, 0.8424, 0.2652],
        [0.1384, 0.1061, 0.1913, 0.0822, 0.8909, 0.4112, 0.9977],
        [0.4365, 0.7412, 0.4072, 0.9046, 0.4486, 0.8666, 0.5380]]) torch.Size([7, 7])


In [7]:
import torch
from torch.autograd import Variable

# Define the tensor 'a' from the previous code
a = Variable(torch.tensor(1.0), requires_grad=True)

# Define a random tensor of shape (1, 7)
random_tensor = torch.rand((1, 7), requires_grad=True)

# Perform matrix multiplication
result = torch.matmul(a, random_tensor)

# Print the result
print("Result of matrix multiplication:")
print(result)

# Compute the gradient
result.backward()

# Print the gradient of 'a'
print("Gradient of 'a':", a.grad)


RuntimeError: both arguments to matmul need to be at least 1D, but they are 0D and 2D

In [8]:
# generate 2 random tensors of size 3X2 and send them to gpu

import torch

a = torch.rand(2,3)
b = torch.rand(2,3)

print('a.device = ',a.device)
print('b.device = ',b.device)

# send to gpu
print(torch.cuda.is_available())

if torch.cuda.is_available():
   a = a.cuda()
   b = b.cuda()

print('a.device = ',a.device)
print('b.device = ',b.device)

a.device =  cpu
b.device =  cpu
True
a.device =  cuda:0
b.device =  cuda:0
